include:
  - path: ./airflow/compose.yml
  - path: ./clickhouse/compose.yml
  - path: ./postgres/compose.yml
  - path: ./spark/compose.yml

volumes:
  postgres-data:
  clickhouse-data:
  clickhouse-logs:

networks:
  bikespark-net:
    driver: bridge
